### ISSUE TITLE
Tidtagnings modul

### ISSUE THREAD

**Issue by VikHolger** [minsulander/vatiris#70]
En modul där man kan starta flera olika tid tagare o döpa dem till olika saker.

Ett exempel på hur det skulle kunna se ut som jag rita för hand
![PXL_20241022_192012759~2.jpg](https://github.com/user-attachments/assets/4c29c8ac-73ab-453c-8571-cc077d672cd0)

**Comment by maxlk96** [comment]
> En modul där man kan starta flera olika tid tagare o döpa dem till olika saker.
> 
> Ett exempel på hur det skulle kunna se ut som jag rita för hand ![PXL_20241022_192012759~2.jpg](https://private-user-images.githubusercontent.com/86929486/378989435-4c29c8ac-73ab-453c-8571-cc077d672cd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjU5NDgsIm5iZiI6MTcyOTYyNTY0OCwicGF0aCI6Ii84NjkyOTQ4Ni8zNzg5ODk0MzUtNGMyOWM4YWMtNzNhYi00NTNjLTg1NzEtY2MwNzdkNjcyY2QwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE5MzQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTc1NzFjODRlMzUxMTc5OWM1NmVlNmJlYzAwMzNlZTU1NmI1MzBjMWEwODRjNjA1ODhjMTgzZTVkOGVhNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.18r593w1vCPi85bRtos-wuImRxGI9A_kFvAr2H2CByU)

Om du klickar på klockan uppe i högra hörnet startar du en timer, den räknar upp och inte ner.

Detta borde inte vara så krångligt att få till!
Tänker du timer(s) som räknar upp och/eller ner?

**Comment by VikHolger** [comment]
Visste inte att man kunde trycka på klockan i hörnet, ska ha det i åtanke i framtiden 

Tänkte nog mest på räknar upp o att man kunde namnge dem. Igår så körde jag på att jag manuellt skrev tiden när EKCK planen startade mot köpenhamn o kom o tänka på att det skulle vara lite härligt att ha dem som en slags timer modul

Hur jag hade VatIRIS uppsat igår
![Screenshot_20241022-214357.png](https://github.com/user-attachments/assets/8c837d90-e613-41a0-8a3b-714f07991c4b)

**Comment by Centiljard** [comment]
Är det här något vi fortfarande vill ha?

**Comment by Centiljard** [comment]
Jag tänker ett fönster per timer. Man kan öppna hur många som helst på samma sätt som man öppnar vanliga fönstermoduler.

**Comment by Centiljard** [comment]
Något sådant här:

<img width="951" alt="Image" src="https://github.com/user-attachments/assets/7b6349e0-b650-473d-b838-6a35992978cc" />

**Comment by prosch35k** [comment]
Men istället för att ha den under ’documents’ göra den nuvarande klockan i högra hörnet till en knapp som blir en drop-down list med ’new timer’, osv?
Och göra all text till stora bokstäver så att det matchar de andra modulerna?

**Comment by Centiljard** [comment]
yes

**Comment by Centiljard** [comment]
Vad är faktiska användningsområdet för timern? Har ni flera uppa samtidigt?

**Comment by Centiljard** [comment]
tänker du något sådant här: <img width="534" alt="Image" src="https://github.com/user-attachments/assets/029ddaf0-cbe5-44cc-a3f5-a6b63b2a4d5b" />

**Comment by Centiljard** [comment]
Annars kan man ju alltid ordna så att man döper den i titelfältet, alltså där det står "TIMER" nu.

**Comment by Centiljard** [comment]
<img width="256" alt="Image" src="https://github.com/user-attachments/assets/71035c27-7566-4bc8-a36d-74bc27ac1228" />

**Comment by maxlk96** [comment]
> Vad är faktiska användningsområdet för timern? Har ni flera uppe samtidigt?

Den nedre förslaget är riktigt snyggt! Man kan lägga till `class: **"no-max"` i Main.vue (frontend\src\views) så finns det mer plats för namnet!

Användningsområde är tex startseparation från en flygplats (därav lätt tillgänglgia 2 och 3 min presets i exemplena längst upp), också för ankomster i ett holding där en får släppas var 10e minut el dyl.

Om man kan få timern att starta om efter den är slut med endast ett knapptryck skulle vara bra av den anledningen, frågan är hur man sköter det snyggt..

**Comment by Centiljard** [comment]
Ja, jag tänker att vi kan ha en submeny under klockan där man kan ladda timers man redan skapat + eventuella preset timers. Sedan kan det också finnas ett menyalternativ  för en timer-skapare. Timerskaparen är en egen fönstermodul för att en eller flera nya timers. Jag ska kolla mer på det imorgon, jag draftar min pull request så länge.

**Comment by minsulander** [comment]
Kul, vilken aktivitet! 😄 
Har haft lite fullt upp de senaste dagarna, ska reviewa och merga så snart jag har möjlighet.

**Comment by Centiljard** [comment]
> Ja, jag tänker att vi kan ha en submeny under klockan där man kan ladda timers man redan skapat + eventuella preset timers. Sedan kan det också finnas ett menyalternativ för en timerskapare.
> 
> Timerskaparen är en egen fönstermodul för att en eller flera nya timers. I skaparen väljer man om timern ska räkna upp eller ned. Är timern en nedräknare tänker jag att den kan ha **en** knapp. Knappen resetar timern och stoppar nedräkningen. Om timern är på noll när man trycker på knappen startar timern om på nytt (resetar och börjar räkna ned igen).
> 
> Ska timern räkna upp får den se ut som det stoppuralternativet vi redan har.
> 
> Det gör ju inget om vi mergar det vi har hittills förresten, så kan vi göra en till pull request för all annan funktionalitet senare. Vi har trots allt den funktionaliteten som issuen handlade om från början. "Tidtagarursmodul"

Jag har sammanställt ett koncept på min branch. Den är i stort sett klar, jag måste bara göra lite buggfixar. Det vore trevligt om ni kunde kolla in den lite och säga vad ni tycker och/eller saknar.

**Comment by Centiljard** [comment]
> @Centiljard 
> 
> Jag kollade in din fork nu, jag lyckas dock inte komma längre än timer creator-fönstret... Det är verkar allt väldigt komplicerat också och nog inte vad jag tänkt mig iallafall. Bara lite enkla timerfönster som [här](https://github.com/minsulander/vatiris/issues/70#issuecomment-2880936238) med möjlighet att manuellt välja tidslängd, ett namn borde inte heller vara tvunget att lägga till, kanske att den lägger till "Timer 1/2/3" osv, och så kan man sedan efter skapandet av den byta namn om så önskas.
> 
> Oavsett hur man nu får upp ett timerfönster så kanske ett av larmljuden från ES-timern (länkad längst upp) skulle kunna spelas upp en gång när timern är slut, och att timerfönstret blinkar i som blue flash i metreport tills man kvitterat den, fast kanske i en annan färg, typ röd eller grå/svart (eller kanske blå ändå för att hålla det enhetligt)? @minsulander 

Hej! Om du klickar på klockan igen dyker timer-fönserna upp i en liten meny.

**Comment by maxlk96** [comment]
> > [@Centiljard](https://github.com/Centiljard)
> > Jag kollade in din fork nu, jag lyckas dock inte komma längre än timer creator-fönstret... Det är verkar allt väldigt komplicerat också och nog inte vad jag tänkt mig iallafall. Bara lite enkla timerfönster som [här](https://github.com/minsulander/vatiris/issues/70#issuecomment-2880936238) med möjlighet att manuellt välja tidslängd, ett namn borde inte heller vara tvunget att lägga till, kanske att den lägger till "Timer 1/2/3" osv, och så kan man sedan efter skapandet av den byta namn om så önskas.
> > Oavsett hur man nu får upp ett timerfönster så kanske ett av larmljuden från ES-timern (länkad längst upp) skulle kunna spelas upp en gång när timern är slut, och att timerfönstret blinkar i som blue flash i metreport tills man kvitterat den, fast kanske i en annan färg, typ röd eller grå/svart (eller kanske blå ändå för att hålla det enhetligt)? [@minsulander](https://github.com/minsulander)
> 
> Hej! Om du klickar på klockan igen dyker timer-fönserna upp i en liten meny. Jag fixade precis så att det finns default-namn på timrarna.

Jo, jag såg det, men det gick inte att öppna timers för mig från den menyn.. 🤔

**Comment by maxlk96** [comment]
Det funkar inte alls för mig..

Jag märkte också att man inte kan skriva sekunder i timern, endast minuter, det skulle behövas båda! (Om man skriver in tex 5.20 så borde det ändras till 5:20, 5 min 20 sek alltså)

![Image](https://github.com/user-attachments/assets/36c00dbf-409a-419b-b455-7b9a9b5d2133)

```

C:\Users\maxlk\Documents\GitHub\Centiljardvatiris\backend>npm start

> vatiris-backend@1.0.0 start
> tsx watch src/server.ts

Server running at http://localhost:5172
  Using VATSIM Auth Base URI: https://auth-dev.vatsim.net/
  Using Client ID: 682
  Using Redirect URI: http://localhost:5173/login
C:\Users\maxlk\Documents\GitHub\Centiljardvatiris\backend\node_modules\pg-pool\index.js:45
    Error.captureStackTrace(err)
          ^

AggregateError [ECONNREFUSED]:
    at C:\Users\maxlk\Documents\GitHub\Centiljardvatiris\backend\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.testQuery (C:\Users\maxlk\Documents\GitHub\Centiljardvatiris\backend\src\db.ts:6:20)
    at async Server.<anonymous> (C:\Users\maxlk\Documents\GitHub\Centiljardvatiris\backend\src\server.ts:24:31) {
  code: 'ECONNREFUSED',
  [errors]: [
    Error: connect ECONNREFUSED ::1:5432
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 5432
    },
    Error: connect ECONNREFUSED 127.0.0.1:5432
        at createConnectionError (node:net:1675:14)
        at afterConnectMultiple (node:net:1705:16) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 5432
    }
  ]
}

Node.js v22.14.0

```

**Comment by Centiljard** [comment]
Har du startat din backend?

**Comment by Centiljard** [comment]
Jag kan kolla på det. Fungerar för mig.

**Comment by Centiljard** [comment]
Jag lyckas inte återskapa felet. Kan det ha och göra med att din databas är uppsatt fel?

**Comment by maxlk96** [comment]
@Centiljard 
Jag körde bara en simpel version av backend utan databas, då beror det nog på det.

Oavsett så är det onödigt krångligt om man ska ha både timer creation-fönstret plus menyn under klockan, förstår inte riktigt idén då som våda delvis väl överlappar varandra?

**Comment by Centiljard** [comment]
Tanken är väl att man skapar alla timers man ska ha någon gång, sedan finns de lättillgängliga under klockmenyn. Sedan kan man alltid gå in och ändra alla man har i editorn senare.
